### ISSUE TITLE
Issue when loading maxent_fast matrices

### ISSUE THREAD

**Issue by SonicNight** [kepbod/maxentpy#4]
from maxentpy.maxent_fast import load_matrix
matrix5 = load_matrix(5)
matrix3 = load_matrix(3)

Traceback (most recent call last):
  File "ensemble_model.py", line 26, in <module>
    matrix3 = load_matrix(3)
  File "/data/miniconda3/envs/mongo3/lib/python3.7/site-packages/maxentpy/maxent_fast.py", line 109, in load_matrix
    matrix = msgpack.unpackb(f.read(), raw=False)
  File "msgpack/_unpacker.pyx", line 194, in msgpack._cmsgpack.unpackb
ValueError: int is not allowed for map key when strict_map_key=True

**Comment by SonicNight** [comment]
Solved by rolling back msgpack-python to version 0.5.6
